query FetchLocalRunReport($owner: String!, $name: String!, $runId: String!) {
  repository(owner: $owner, name: $name) {
    run(id: $runId) {
     id
      status
      url
      results {
        time
        benchmark {
          name
          uri
        }
      }
    }
  }
}
